### ISSUE TITLE
shell text garbled on M2 mac

### ISSUE THREAD

**Issue by hiromaily** [zimfw/eriner#2]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
shell text is garbled like `~/g/s/g/h/go-crypto-wallet   master `
I installed font with Powerline symbols and git-info as requirements.

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Other steps to reproduce the behavior

**Current behavior**  
shell text is garbled like the following image

<img width="311" alt="Screen Shot 2022-08-03 at 0 16 42" src="https://user-images.githubusercontent.com/301692/182411001-f2cce903-bccc-4409-bb80-4faaa7622f94.png">

**Expected behavior**  
no garbled text

**zimfw info**  
```
# In a terminal, run zimfw info, and paste the output here.
zimfw version: 1.9.1 (built at 2022-05-24 21:25:10 UTC, previous commit is 5bcfb8c)
ZIM_HOME:      /Users/hy/.config/zsh/.zim
Zsh version:   5.8.1
System info:   Darwin HYs-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64
```

**Comment by ericbn** [comment]
Hi @hiromaily. This pretty much looks like the Powerline font was not enabled in your terminal emulator. Check https://stackoverflow.com/q/42271657/2654518

**Comment by hiromaily** [comment]
@ericbn 
Thanks for your quick reply and I fixed this problem :)
