### ISSUE TITLE
Visual prompt bug

### ISSUE THREAD

**Issue by BrainMaestro** [zimfw/eriner#3]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

When used with zsh autosuggestions (triggered by hitting tab), the prompt incorrectly includes any text written before the suggestions which looks like
<img width="244" alt="image" src="https://github.com/zimfw/eriner/assets/1738373/f5a5088a-888c-4fc3-aeab-b8dd431e8af4">

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. `Add more steps here ...`
Add `zmodule eriner` to your .zimrc

3. Type part of a command and hit tab for suggestions. The visual glitch with the prompt should be present

### Current behavior

Prompt includes text type by the user that cannot be deleted 
![Eriner-Bug](https://github.com/zimfw/eriner/assets/1738373/19b4379a-8d73-45e6-97db-a9c5cbec7ae0)


### Expected behavior

Prompt should not include any direct user shell input

### zimfw info

_No response_

### Additional context

zsh 5.9 (x86_64-apple-darwin22.0)
HEAD of zimfw and eriner (both cloned today 2023-09-09)

**Comment by ericbn** [comment]
Hi @BrainMaestro. This is not an uncommon issue and you might find other users asking the same questions elsewhere. Check https://github.com/zimfw/zimfw/issues/504, https://github.com/starship/starship/issues/4669 and https://stackoverflow.com/q/19305291/2654518

**Comment by BrainMaestro** [comment]
Oh thank you! I tried with other themes and it didn't exhibit the same behaviour, so I thought it originated from here. Thanks for the quick response. Setting the env variable fixed it
