### ISSUE TITLE
Missing hostname on M3 MacBook Pro

### ISSUE THREAD

**Issue by LittleNewton** [zimfw/eriner#4]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

Hi Mr. Eric, details of my issue can be found [here](https://github.com/zimfw/zimfw/issues/532).

I am using `eriner` theme and I love it so much.

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. `Add more steps here ...`


### Current behavior

No hostname is shown.

### Expected behavior

It should be shown.

### zimfw info

```shell
zimfw version:        1.13.0 (built at 2024-02-17 02:05:06 UTC, previous commit is 9de3984)
LANG:                 zh_CN.UTF-8
LC_TERMINAL_VERSION:  3.4.23
LC_TERMINAL:          iTerm2
LC_CTYPE:             en_US.UTF-8
OSTYPE:               darwin23.0
TERM:                 xterm-256color
TERM_PROGRAM:         iTerm.app
TERM_PROGRAM_VERSION: 3.4.23
ZIM_HOME:             /Users/newton/.local/share/zim
ZSH_VERSION:          5.9
```
```


### Additional context

_No response_

**Comment by ericbn** [comment]
@LittleNewton check the [What does it show?](https://github.com/zimfw/eriner/blob/master/README.md#what-does-it-show) section the README.md. It says:

> username@hostname when in a ssh session.

It only shows the user@hostname when you're in a ssh session, not locally.
